apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: redis-deployment
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        # Label is used as selector in the service.
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          hostPort: 6379
        command: ["redis-server", "--appendonly", "yes"]
        # Mount the volume into the pod
        volumeMounts:
        - name: redis-storage # must match the volume name, bellow
          mountPath: "/data"
      # Refer to the PVC created earlier
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          # Name of the PVC created earlier
          claimName: redis-pv-claim
          
